# Learning Rate & Evaluation    

- 핵심 : 데이터 셋을 Training/Testing set으로 나눔. 

In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]     # Training set : 학습 시에 사용 

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]   # Testing set : 학습이 끝난 뒤 성능 평가시 사용. 

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [2]:
# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

        # Prediction / Accuracy를 측정할 경우에 Test데이터 셋을 사용. 
    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


0 5.73203 [[ 0.7288166   0.7153621  -1.1801533 ]
 [-0.5775373  -0.1298833   1.6072978 ]
 [ 0.48373488 -0.51433605 -2.02127   ]]
1 3.317995 [[ 0.6621908   0.74796313 -1.1461285 ]
 [-0.81948906  0.03000022  1.689366  ]
 [ 0.23214608 -0.33772916 -1.9462881 ]]
2 2.0218027 [[ 0.6434202   0.7412768  -1.1206716 ]
 [-0.8116129  -0.00900117  1.7204912 ]
 [ 0.20866647 -0.35079566 -1.909742  ]]
3 1.9710885 [[ 0.6235321   0.7400823  -1.099589  ]
 [-0.80967706 -0.01636278  1.725917  ]
 [ 0.17870611 -0.3366575  -1.8939198 ]]
4 1.9446772 [[ 0.60733104  0.7366498  -1.0799555 ]
 [-0.79007834 -0.03363192  1.7235874 ]
 [ 0.16691463 -0.33406347 -1.8847224 ]]
5 1.9235673 [[ 0.59031737  0.73510236 -1.0613943 ]
 [-0.77496755 -0.04048847  1.7153332 ]
 [ 0.15076597 -0.32209396 -1.8805432 ]]
6 1.9035923 [[ 0.57437915  0.7326285  -1.0429822 ]
 [-0.75527763 -0.05152     1.7066748 ]
 [ 0.13977788 -0.31497923 -1.8766699 ]]
7 1.88408 [[ 0.5581266   0.73071784 -1.024819  ]
 [-0.7377567  -0.05928203  1.696916  ]
 [ 0.

65 1.1785977 [[-0.19840932  0.5643028  -0.101868  ]
 [-0.07647492 -0.16092637  1.1372788 ]
 [-0.24052751 -0.184639   -1.6267042 ]]
66 1.1708336 [[-0.20871137  0.5610877  -0.08835089]
 [-0.06990003 -0.1583327   1.1281103 ]
 [-0.24355999 -0.18655089 -1.6217599 ]]
67 1.1631591 [[-0.21893871  0.55787784 -0.07491367]
 [-0.06341317 -0.15567777  1.1189685 ]
 [-0.24653873 -0.18851885 -1.6168132 ]]
68 1.1555727 [[-0.2290923   0.5546738  -0.06155602]
 [-0.05701218 -0.1529643   1.109854  ]
 [-0.24946535 -0.19054022 -1.6118652 ]]
69 1.148073 [[-0.23917305  0.5514761  -0.04827759]
 [-0.05069481 -0.15019517  1.1007675 ]
 [-0.25234115 -0.19261262 -1.6069169 ]]
70 1.1406591 [[-0.2491819   0.5482854  -0.03507805]
 [-0.044459   -0.14737299  1.0917095 ]
 [-0.25516757 -0.19473353 -1.6019696 ]]
71 1.1333299 [[-0.25911975  0.54510224 -0.02195704]
 [-0.03830272 -0.14450039  1.0826806 ]
 [-0.25794587 -0.19690065 -1.5970242 ]]
72 1.1260841 [[-0.26898748  0.54192716 -0.00891422]
 [-0.03222401 -0.14157994  1.073

143 0.7835874 [[-0.8331474   0.35734326  0.7398297 ]
 [ 0.26552778  0.08669894  0.5476505 ]
 [-0.3673941  -0.3738747  -1.3106018 ]]
144 0.78073025 [[-0.83961636  0.35546455  0.74817735]
 [ 0.26828814  0.08931624  0.54227287]
 [-0.36783594 -0.37574774 -1.3082869 ]]
145 0.7779149 [[-0.8460534   0.35360688  0.7564721 ]
 [ 0.27101502  0.09190372  0.5369585 ]
 [-0.36825052 -0.37759265 -1.3060274 ]]
146 0.7751408 [[-0.8524589   0.35177016  0.7647143 ]
 [ 0.2737086   0.09446116  0.53170747]
 [-0.368638   -0.37940946 -1.3038231 ]]
147 0.7724074 [[-0.85883313  0.34995434  0.77290434]
 [ 0.27636904  0.09698859  0.5265196 ]
 [-0.36899862 -0.38119805 -1.3016739 ]]
148 0.76971394 [[-0.8651764   0.34815934  0.7810426 ]
 [ 0.27899665  0.09948579  0.5213948 ]
 [-0.36933234 -0.3829585  -1.2995797 ]]
149 0.76706 [[-0.8714889   0.3463851   0.7891294 ]
 [ 0.28159145  0.10195282  0.516333  ]
 [-0.36963955 -0.3846907  -1.2975403 ]]
150 0.7644448 [[-0.877771    0.3446315   0.7971651 ]
 [ 0.28415382  0.104389

## Learning Rate 설정의 중요성
- Large Learning Rate(Overshooting) : 값에 수렴하지 않고 발산함.    
- Small Learning Rate : 학습이 안될수 있고, local minimum에 빠질 가능성 존재. 

In [3]:
# 1. Big Learning Rate
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)  # Learning R0ate를 1.5로 크게 설정 
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


'''
0 Cost:  2.45533e+12
Prediction:
 [[-1104436.375]
 [-2224342.75 ]
 [-1749606.75 ]
 [-1226179.375]
 [-1445287.125]
 [-1457459.5  ]
 [-1335740.5  ]
 [-1700924.625]]
1 Cost:  2.69762e+27
Prediction:
 [[  3.66371490e+13]
 [  7.37543360e+13]
 [  5.80198785e+13]
 [  4.06716290e+13]
 [  4.79336847e+13]
 [  4.83371348e+13]
 [  4.43026590e+13]
 [  5.64060907e+13]]
2 Cost:  inf
Prediction:
 [[ -1.21438790e+21]
 [ -2.44468702e+21]
 [ -1.92314724e+21]
 [ -1.34811610e+21]
 [ -1.58882674e+21]
 [ -1.60219962e+21]
 [ -1.46847142e+21]
 [ -1.86965602e+21]]
3 Cost:  inf
Prediction:
 [[  4.02525216e+28]
 [  8.10324465e+28]
 [  6.37453079e+28]
 [  4.46851237e+28]
 [  5.26638074e+28]
 [  5.31070676e+28]
 [  4.86744608e+28]
 [  6.19722623e+28]]
4 Cost:  inf
Prediction:
 [[ -1.33422428e+36]
 [ -2.68593010e+36]
 [ -2.11292430e+36]
 [ -1.48114879e+36]
 [ -1.74561303e+36]
 [ -1.76030542e+36]
 [ -1.61338091e+36]
 [ -2.05415459e+36]]
5 Cost:  inf                 # 값이 발산, 무한대로 되어버림. 
Prediction:
 [[ inf]
 [ inf]
 [ inf]
 [ inf]
 [ inf]
 [ inf]
 [ inf]
 [ inf]]
6 Cost:  nan                # Learning Rate 값이 발산, 학습 포기 
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
'''

0 Cost:  2519696000000.0 
Prediction:
 [[1120640. ]
 [2254801.8]
 [1774008. ]
 [1243901.9]
 [1465808. ]
 [1478132.2]
 [1354844.1]
 [1724677.5]]
1 Cost:  2.7683398e+27 
Prediction:
 [[-3.7114276e+13]
 [-7.4714840e+13]
 [-5.8775474e+13]
 [-4.1201294e+13]
 [-4.8557927e+13]
 [-4.8966629e+13]
 [-4.4879611e+13]
 [-5.7140669e+13]]
2 Cost:  inf 
Prediction:
 [[1.2302029e+21]
 [2.4765244e+21]
 [1.9481925e+21]
 [1.3656725e+21]
 [1.6095181e+21]
 [1.6230651e+21]
 [1.4875953e+21]
 [1.8940044e+21]]
3 Cost:  inf 
Prediction:
 [[-4.0776733e+28]
 [-8.2087735e+28]
 [-6.4575462e+28]
 [-4.5267056e+28]
 [-5.3349646e+28]
 [-5.3798682e+28]
 [-4.9308354e+28]
 [-6.2779334e+28]]
4 Cost:  inf 
Prediction:
 [[1.3516000e+36]
 [2.7209090e+36]
 [2.1404410e+36]
 [1.5004378e+36]
 [1.7683461e+36]
 [1.7832299e+36]
 [1.6343921e+36]
 [2.0809058e+36]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]

'\n0 Cost:  2.45533e+12\nPrediction:\n [[-1104436.375]\n [-2224342.75 ]\n [-1749606.75 ]\n [-1226179.375]\n [-1445287.125]\n [-1457459.5  ]\n [-1335740.5  ]\n [-1700924.625]]\n1 Cost:  2.69762e+27\nPrediction:\n [[  3.66371490e+13]\n [  7.37543360e+13]\n [  5.80198785e+13]\n [  4.06716290e+13]\n [  4.79336847e+13]\n [  4.83371348e+13]\n [  4.43026590e+13]\n [  5.64060907e+13]]\n2 Cost:  inf\nPrediction:\n [[ -1.21438790e+21]\n [ -2.44468702e+21]\n [ -1.92314724e+21]\n [ -1.34811610e+21]\n [ -1.58882674e+21]\n [ -1.60219962e+21]\n [ -1.46847142e+21]\n [ -1.86965602e+21]]\n3 Cost:  inf\nPrediction:\n [[  4.02525216e+28]\n [  8.10324465e+28]\n [  6.37453079e+28]\n [  4.46851237e+28]\n [  5.26638074e+28]\n [  5.31070676e+28]\n [  4.86744608e+28]\n [  6.19722623e+28]]\n4 Cost:  inf\nPrediction:\n [[ -1.33422428e+36]\n [ -2.68593010e+36]\n [ -2.11292430e+36]\n [ -1.48114879e+36]\n [ -1.74561303e+36]\n [ -1.76030542e+36]\n [ -1.61338091e+36]\n [ -2.05415459e+36]]\n5 Cost:  inf\nPrediction:\n 

In [4]:
# 2. Small Learning Rate
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

# very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

'''
[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
'''

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost) # Learning rate를 아주 작게 설정 

# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(101):
        _, cost_val, hy_val = sess.run(
            [train, cost, hypothesis], feed_dict={X: x_data, Y: y_data}
        )
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
0 Cost: 0.15230925 
Prediction:
 [[ 1.6346191 ]
 [ 0.06613699]
 [ 0.3500818 ]
 [ 0.6707252 ]
 [ 0.61130744]
 [ 0.61464405]
 [ 0.23171967]
 [-0.1372836 ]]
1 Cost: 0.15230872 
Prediction:
 [[ 1.634618  ]
 [ 0.06613836]
 [ 0.35008252]
 [ 0.670725  ]
 [ 0.6113076 ]
 [ 0.6146443 ]
 [ 0.23172   ]
 [-0.13728246]]
...
99 Cost: 0.1522546 
Prediction:
 [[ 1.6345041 ]
 [ 0.06627947]
 [ 0.35014683]
 [ 0.670706  ]
 [ 0.6113161 ]
 [ 0.61466044]
 [ 0.23175153]
 [-0.13716647]]
100 Cost: 0.15225402 
Prediction:
 [[ 1.6345029 ]
 [ 0.06628093]
 [ 0.35014752]
 [ 0.67070574]
 [ 0.61131614]
 [ 0.6146606 ]
 [ 0.23175186]
 [-0.13716528]]                # 학습을 여러번 하여도 Cost 값이 같음. 
'''

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost:  6.008363 
Prediction:
 [[-2.787303  ]
 [-2.304973  ]
 [-1.9524162 ]
 [-1.5445647 ]
 [-1.8520749 ]
 [-1.818827  ]
 [-1.0787338 ]
 [-0.97747326]]
1 Cost:  6.00791 
Prediction:
 [[-2.7871776 ]
 [-2.304853  ]
 [-1.9523162 ]
 [-1.5444871 ]
 [-1.851983  ]
 [-1.8187382 ]
 [-1.078675  ]
 [-0.97741604]]
2 Cost:  6.007457 
Prediction:
 [[-2.7870522]
 [-2.304733 ]
 [-1.9522161]
 [-1.5444096]
 [-1.851891 ]
 [-1.8186496]
 [-1.0786163]
 [-0.9773588]]
3 Cost:  6.007004 
Prediction:
 [[-2.786927 ]
 [-2.304613 ]
 [-1.9521161]
 [-1.544332

58 Cost:  5.982153 
Prediction:
 [[-2.7800405]
 [-2.2980225]
 [-1.9466207]
 [-1.5400733]
 [-1.8467491]
 [-1.813688 ]
 [-1.0753295]
 [-0.9741574]]
59 Cost:  5.9817023 
Prediction:
 [[-2.7799153]
 [-2.2979028]
 [-1.9465208]
 [-1.5399959]
 [-1.8466573]
 [-1.8135996]
 [-1.075271 ]
 [-0.9741003]]
60 Cost:  5.9812517 
Prediction:
 [[-2.7797904]
 [-2.2977831]
 [-1.9464211]
 [-1.5399185]
 [-1.8465655]
 [-1.8135109]
 [-1.0752124]
 [-0.9740432]]
61 Cost:  5.9808006 
Prediction:
 [[-2.7796652]
 [-2.2976635]
 [-1.9463212]
 [-1.5398412]
 [-1.8464739]
 [-1.8134224]
 [-1.0751537]
 [-0.9739861]]
62 Cost:  5.9803495 
Prediction:
 [[-2.77954   ]
 [-2.2975438 ]
 [-1.9462214 ]
 [-1.5397639 ]
 [-1.8463821 ]
 [-1.813334  ]
 [-1.0750952 ]
 [-0.97392905]]
63 Cost:  5.9798985 
Prediction:
 [[-2.779415  ]
 [-2.2974238 ]
 [-1.9461217 ]
 [-1.5396866 ]
 [-1.8462903 ]
 [-1.8132455 ]
 [-1.0750365 ]
 [-0.97387195]]
64 Cost:  5.9794483 
Prediction:
 [[-2.77929   ]
 [-2.2973044 ]
 [-1.9460218 ]
 [-1.5396092 ]
 [-1.8461

'\n0 Cost: 0.15230925 \nPrediction:\n [[ 1.6346191 ]\n [ 0.06613699]\n [ 0.3500818 ]\n [ 0.6707252 ]\n [ 0.61130744]\n [ 0.61464405]\n [ 0.23171967]\n [-0.1372836 ]]\n1 Cost: 0.15230872 \nPrediction:\n [[ 1.634618  ]\n [ 0.06613836]\n [ 0.35008252]\n [ 0.670725  ]\n [ 0.6113076 ]\n [ 0.6146443 ]\n [ 0.23172   ]\n [-0.13728246]]\n...\n99 Cost: 0.1522546 \nPrediction:\n [[ 1.6345041 ]\n [ 0.06627947]\n [ 0.35014683]\n [ 0.670706  ]\n [ 0.6113161 ]\n [ 0.61466044]\n [ 0.23175153]\n [-0.13716647]]\n100 Cost: 0.15225402 \nPrediction:\n [[ 1.6345029 ]\n [ 0.06628093]\n [ 0.35014752]\n [ 0.67070574]\n [ 0.61131614]\n [ 0.6146606 ]\n [ 0.23175186]\n [-0.13716528]]\n'

### NaN(Non-normalized inputs)
:해결 --> Nomalized inputs(Min-max scaler), 모든 값들을 Min-max scaler를 통해 정규화를 한다.