# Softmax Classification, 다항 분류
n개의 예측할 것들이 있을 경우 softmax classification을 한다.     
softmax : 모든 클래스의 값들을 합치면 1이 되게 함

In [1]:
import tensorflow as tf
tf.set_random_seed(777)
 
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1], 
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]   # 'One-hot encoding'으로 표시.

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3]) # One-hot encoding으로 표시할때는 클래스의 개수로 shape을 지정한다. 
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')  # [x값, 출력 클래스의 값]
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [4]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
# tensorflow에서 softmax 함수 라이브러리 제공
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# 어떤 레이블이 될것이나에 대한 확률이 나옴. 

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
            _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})

            if step % 200 == 0:
                print(step, cost_val)

    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

                

0 6.926112
200 0.60050154
400 0.47295803
600 0.37342966
800 0.2801839
1000 0.23280522
1200 0.21065351
1400 0.19229898
1600 0.17682323
1800 0.16359563
2000 0.15216146
--------------
[[1.3890452e-03 9.9860197e-01 9.0613094e-06]] [1]
--------------
[[0.9311919  0.0629022  0.00590593]] [0]
--------------
[[1.2732791e-08 3.3411323e-04 9.9966586e-01]] [2]
--------------
[[1.3890452e-03 9.9860197e-01 9.0613185e-06]
 [9.3119192e-01 6.2902182e-02 5.9059174e-03]
 [1.2732791e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]
